name: Terraform Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight (UTC)
    #- cron: '*/1 * * * *' #Runs immediately

jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.5.7' 
      TF_WORKSPACE: default

    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Terraform Init'
        working-directory: env/dev
        run: terraform init

      - name: 'Terraform Plan Destroy'
        working-directory: env/dev
        run: terraform plan -destroy -var="alert_email=${{ secrets.ALERT_EMAIL }}" -out=tfplan-destroy

      - name: 'Terraform Apply Destroy'
        working-directory: env/dev
        run: terraform apply -auto-approve tfplan-destroy
